name: AMR_ML
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates
  - certifi=2019.11.28=py36_0
  - cycler=0.10.0=py36_0
  - dbus
  - expat
  - fontconfig
  - freetype
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - intel-openmp
  - joblib
  - jpeg
  - kiwisolver
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libstdcxx-ng
  - libuuid
  - libxcb
  - libxml2
  - matplotlib
  - mkl
  - mkl_fft
  - mkl_random
  - ncurses
  - numpy
  - numpy-base
  - openssl
  - pandas
  - pcre
  - pip
  - pyparsing
  - pyqt
  - python=3.6.8
  - python-dateutil
  - pytz
  - qt
  - readline
  - scikit-learn
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - tornado
  - wheel
  - xz
  - zlib
